session_name: LLM-Analysis
windows:
  - window_name: LLM-Analysis
    layout: main-vertical
    options:
      main-pane-width: 20%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/llm-archive-analysis
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 85%
          - filelist-open "startup_files.txt" llm-archive-analysis
        focus: true
      - clear
